---
# Host-specific vars for the lostsecret-intel host
ansible_become_password: ""  # Password for sudo if not using passwordless sudo
ansible_connection: local  # Connection method (local for this host)
ansible_python_interpreter: "/usr/bin/python3"  # Python interpreter path
