---
# Base role: tasks that should always be true on lostsecret-intel

- name: Check connectivity
  ansible.builtin.ping:
  become: no

# - name: Ensure apt cache is up to date
#   ansible.builtin.apt:
#     update_cache: true
#     cache_valid_time: 3600

# - name: Ensure common packages are installed
#   ansible.builtin.apt:
#     name:
#       - vim
#       - htop
#     state: present

# - name: Get Power through redfish
#   ansible.builtin.command: >
#     /usr/bin/python3 {{ role_path }}/files/get_power_redfish.py
#     {{ inventory_hostname }}
#     {{ bmc_user }}
#     {{ bmc_pass }}
#   delegate_to: localhost
#   register: power_output

# - name: Show the Watts
#   ansible.builtin.debug:
#     msg: "Server is consuming {{ (power_output.stdout | from_json).watts }} Watts"

# - name: Hello World
#   ansible.builtin.command: /usr/bin/python3 {{ role_path }}/files/hello_world.py
#   delegate_to: localhost

- name: get power through rapl
  ansible.builtin.command: > # arg1: interval
    /bin/bash {{ role_path }}/files/get_power_rapl_no_deps.bash
    10
  delegate_to: localhost
  become: no
  register: rapl_power_output
  failed_when: rapl_power_output.rc != 0