---
- name: Deploy power monitoring framework
  hosts: lostsecret_intel:lostsecret_amd
  become: yes
  gather_facts: no

  vars:
    power_monitoring_enable_cpu: auto
    power_monitoring_enable_ram: auto
    power_monitoring_enable_gpu: auto
    power_monitoring_enable_redfish: auto

  roles:
    - role: power_monitoring
